# Numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.

In this notebook, you will find 30 exercises that are essential to practice and learn numpy. If you want to do further exploration, you can continue working on `02.Extra_Drill_numpy.ipynb`.

#### 1. Import the numpy package under the name `np` (★☆☆)

In [2]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [3]:
print(np.__version__)

1.22.3


#### 3. Create a null vector of size 10 (★☆☆)

In [4]:
X=np.zeros(10)
print(X)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. How to find the memory size of any array (★☆☆)

In [5]:
X.size

10

#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [6]:
print(np.info(np.add))

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [7]:
X=np.zeros(10)
X[4]=1
print(X)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [8]:
x=np.arange(10,50)
print(x)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [9]:
x=x[::-1]
print(x)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [10]:
a=np.arange(0,9).reshape(3,3)
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [11]:
x=[1,2,0,0,4,0]
np.nonzero(x)

(array([0, 1, 4], dtype=int64),)

#### 11. Create a 3x3 identity matrix (★☆☆)

In [12]:
array=np.identity(3)
print(array)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [13]:
np.random.random((3,3,3))

array([[[0.25145757, 0.04624046, 0.30275702],
        [0.5633281 , 0.09152555, 0.63123317],
        [0.87186386, 0.2667621 , 0.20197701]],

       [[0.17070347, 0.43005269, 0.98240457],
        [0.93830095, 0.18660945, 0.11381082],
        [0.43083063, 0.57829301, 0.47624705]],

       [[0.55618395, 0.22505809, 0.8000193 ],
        [0.77969736, 0.18976349, 0.39998269],
        [0.90841079, 0.04209061, 0.28424116]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [14]:
a = np.random.random((10,10))
a_min, a_max = a.min(), a.max()
print("minimum=",a_min,"maximum=",a_max)

minimum= 0.015101157060890102 maximum= 0.9962162817757578


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [15]:
x = np.random.random(30)
print(x)
print("mean=",a.mean())


[0.21627513 0.29032057 0.12591164 0.44682229 0.32998072 0.77338808
 0.79666301 0.84839878 0.69594864 0.59897581 0.97472749 0.34057144
 0.59189167 0.95158688 0.91303077 0.65775934 0.58967201 0.65858181
 0.95344968 0.54554936 0.84507899 0.83874927 0.47345724 0.93438518
 0.59802658 0.56924221 0.1520602  0.98810765 0.50706117 0.1429394 ]
mean= 0.5146475469904304


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [16]:
a = np.ones((7,7))
print(a)  #original array
a[1:-1,1:-1] = 0 
print(a)  #array with 1 on the border and 0 inside

[[1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]
[[1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [17]:
a = np.pad(a, pad_width=1, mode='constant', constant_values=0)
print(a)

[[0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 0. 0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0. 0. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [18]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [19]:
X = np.diag([1,2,3,4],-1)
print(X)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [20]:
a=np.ones((8,8))
a[1::2,0::2]=0
a[0::2,1::2]=0
print(a)

[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [21]:
x=np.random.random((6,7,8))
result=np.where(x == 100)
print(result)
#print (np.unravel_index(100,(6,7,8)))

(array([], dtype=int64), array([], dtype=int64), array([], dtype=int64))


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [22]:
a = np.tile(np.array([[0,1],[1,0]]),(4,4))
print(a)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [23]:
x=np.random.random((3,3))
print("Original array:")
print(x)
x_min,x_max= x.min(),x.max()
x=(x-x_min)/(x_max-x_min)
print("After normalization:")
print(x)

Original array:
[[0.18551797 0.49537838 0.5022758 ]
 [0.75479505 0.22495745 0.52768115]
 [0.26332068 0.52433486 0.55970747]]
After normalization:
[[0.         0.54430509 0.55642119]
 [1.         0.06927995 0.60104859]
 [0.13666931 0.59517044 0.65730646]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [24]:
color=np.dtype([("r",np.ubyte),("g",np.ubyte),("b",np.ubyte),("a",np.ubyte)])
print(color)

[('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')]


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [25]:
x=np.random.random((5,3))
y=np.random.random((3,2))
print("Original arrays:",x,y)
z=x.dot(y)
print("Arrays with dot",z)

Original arrays: [[0.17090061 0.71067793 0.01033944]
 [0.15765535 0.70664485 0.46381808]
 [0.01934665 0.800917   0.71882526]
 [0.97268424 0.43439185 0.01475368]
 [0.94399083 0.01454348 0.36812345]] [[0.12904342 0.4307205 ]
 [0.59855267 0.16435735]
 [0.42034582 0.41636321]]
Arrays with dot [[0.45177791 0.1947205 ]
 [0.63827254 0.37716446]
 [0.78404276 0.43926199]
 [0.39172655 0.49649343]
 [0.28526    0.56225959]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [26]:
x=np.arange(11)
print(x)
x[(3<x)&(x<8)]*= -1
print("array after negate:",x)

[ 0  1  2  3  4  5  6  7  8  9 10]
array after negate: [ 0  1  2  3 -4 -5 -6 -7  8  9 10]


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [27]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [28]:
Z=np.arange(10)
print(Z**Z) 
print(2 << Z >> 2) 
print(Z <- Z) 
print(1j*Z) 
print(Z/1/1)
print(Z<Z>Z) 

[        1         1         4        27       256      3125     46656
    823543  16777216 387420489]
[  0   1   2   4   8  16  32  64 128 256]
[False False False False False False False False False False]
[0.+0.j 0.+1.j 0.+2.j 0.+3.j 0.+4.j 0.+5.j 0.+6.j 0.+7.j 0.+8.j 0.+9.j]
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

#### 28. What are the result of the following expressions?
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [29]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-2.14748365e+09]


C:\Users\HP\AppData\Local\Temp\ipykernel_10500\3912170336.py:1: RuntimeWarning: invalid value encountered in true_divide
  print(np.array(0) / np.array(0))
C:\Users\HP\AppData\Local\Temp\ipykernel_10500\3912170336.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))


#### 29. How to round away from zero a float array ? (★☆☆)

In [30]:
x=np.random.random((1,2,3))
print(x)
y=np.round(x,0)
print(y)

[[[0.06872389 0.76462294 0.12093608]
  [0.48170771 0.3223326  0.52694514]]]
[[[0. 1. 0.]
  [0. 0. 1.]]]


#### 30. How to find common values between two arrays? (★☆☆)

In [31]:
arr1=[10,20,30,40,50,60,70]
arr2=[20,80,50,70,90]
common=np.intersect1d(arr1,arr2)
print(common)

[20 50 70]
